### PR TITLE
Refactor crate dependencies

### PR DESCRIPTION
**Pull request by src255**
Move common dependencies to workspace dependencies. 

**Note:** some dependency versions of the form "X.Y" are now "~X.Y" to be consistent with other similar imports.

### CODE REVIEW

**Comment by cdata** [comment]
Thank you for making this contribution @src255 ! This is relevant to #64 .

I admit, I hadn't read the documentation thoroughly. In the issue description, I speculated that this change would cut down on bloat. But, sadly that is not the case (since you must still inherit the dependency explicitly in the crate's manifest).

That said, this change still seems valuable for ensuring that our dependency versions are consistent across the workspace.

**Comment by cdata** [comment]
@src255 looks like we have a build failure: https://github.com/subconsciousnetwork/noosphere/actions/runs/3132929628/jobs/5095833286

Please take a look, and I'll check back here when you have a resolution!

**Comment by src255** [comment]
Apologies, I introduced a typo in *rust/noosphere/Cargo.toml* during refactoring. I think this was the only issue.

**rust/noosphere/Cargo.toml**
```diff
-ed25519.workspace = true
+ed25519-zebra.workspace = true
```

**Comment by cdata** [comment]
Oh, one more thing: we require signed commits as a merge policy. Would you be willing to sign your commits?

https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits

**Review by cdata — DISMISSED** [review]
Thank you so much for taking on this task! :beers:

**Comment by src255** [comment]
No problem! I just moved **axum** and **tower-http** from the workspace dependencies back to the individual Cargo.toml files.

**Pull request closed without merging**
