### PR TITLE
Convert NameSystem/DHTNode to be generic over keys (DHTKeyMaterial).

### PR DESCRIPTION
**Pull request by jsantell**

### CODE REVIEW

**Comment by cdata** [comment]
This looks good. I think this has marginal overlap with #162 . Would you be willing to try your hand at rebasing onto that change to see what the delta is? If it's not major, I might suggest we try to land #162 first (but if it is too hairy, we can land this one first).

**Comment by jsantell** [comment]
@cdata No rebase issues here! Conflicts were in the orb-ns binary (rebased in #159)

**Review by cdata — APPROVED** [review]
Nice, the extra `Clone` bound is needed!

**Review by cdata — APPROVED** [review]

**Review by cdata — APPROVED** [review]
Let's gooo!

**Pull request merged**
