### PR TITLE
chore: Remove noosphere-car from tree, now replaced by iroh-car. Fixes #493

### LINKED ISSUE #493: Remove noosphere-car after publishing deprecation
After #492 lands, replacing noosphere-car with iroh-car, and publishing a deprecated version of the noosphere-car crate, we'll be able to remove it from our workspace.

### PR DESCRIPTION
**Pull request by jsantell**

### CODE REVIEW

**Comment by cdata** [comment]
Weren't we going to publish a `+deprecated` version first?

**Comment by jsantell** [comment]
> Weren't we going to publish a `+deprecated` version first?

let's do it!

**Comment by cdata** [comment]
This needs a rebase before we can properly land it.

**Review by cdata — APPROVED** [review]
LGTM but needs some Cargo.lock conflict resolution (sorry)

**Review by cdata — APPROVED** [review]

**Pull request merged**
